require('dotenv').config();
const express = require('express');
const cookieParser = require('cookie-parser');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const crypto = require('crypto');
const path = require('path');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const store = require('./db');

const app = express();
const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET;
const SETUP_KEY = process.env.SETUP_KEY;
const INTEGRATION_KEY = process.env.INTEGRATION_KEY;
const IS_PRODUCTION = process.env.NODE_ENV === 'production';

if (!JWT_SECRET || JWT_SECRET.length < 32) { console.error('Missing/weak JWT_SECRET.'); process.exit(1); }
if (!SETUP_KEY || SETUP_KEY.length < 12) { console.error('Missing/weak SETUP_KEY.'); process.exit(1); }
if (!INTEGRATION_KEY || INTEGRATION_KEY.length < 16) { console.error('Missing/weak INTEGRATION_KEY.'); process.exit(1); }
if (!process.env.UPSTASH_REDIS_REST_URL || !process.env.UPSTASH_REDIS_REST_TOKEN) { console.error('Missing UPSTASH_REDIS_REST_URL or UPSTASH_REDIS_REST_TOKEN.'); process.exit(1); }

app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use(helmet({
  crossOriginResourcePolicy: { policy: 'cross-origin' },
  contentSecurityPolicy: { directives: {
    defaultSrc: ["'self'"], scriptSrc: ["'self'", "'unsafe-inline'"], scriptSrcAttr: ["'unsafe-inline'"],
    styleSrc: ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com'], styleSrcAttr: ["'unsafe-inline'"],
    fontSrc: ["'self'", 'https://fonts.gstatic.com'], imgSrc: ["'self'", 'data:', 'https:'], connectSrc: ["'self'"],
    objectSrc: ["'none'"], baseUri: ["'self'"], formAction: ["'self'"], frameAncestors: ["'self'"],
  }}
}));
app.use(express.json({ limit: '500kb' }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

const loginLimiter = rateLimit({ windowMs: 15*60*1000, limit: 15, standardHeaders: true, legacyHeaders: false, message: { error: 'Too many login attempts. Please try again later.' } });
const setupLimiter = rateLimit({ windowMs: 60*60*1000, limit: 5, standardHeaders: true, legacyHeaders: false, message: { error: 'Too many setup attempts. Please try again later.' } });
const integrationLimiter = rateLimit({ windowMs: 60*1000, limit: 120, standardHeaders: true, legacyHeaders: false, message: { error: 'Too many integration requests. Please slow down.' } });

const PIPELINE_STAGES = ['new','contacted','processing','awaiting_payment','fulfilled','won','lost','cancelled'];
const TASK_STATUSES = ['open','in_progress','done'];
function newId(prefix) { return prefix + '-' + crypto.randomBytes(5).toString('hex'); }
function cleanText(value, max=500) { return String(value ?? '').trim().slice(0,max); }
function normalizePhone(value) { return String(value ?? '').replace(/[^\d+]/g,'').slice(0,20); }
function now() { return new Date().toISOString(); }
function safeEqual(a,b) { const A=Buffer.from(String(a??'')), B=Buffer.from(String(b??'')); if(A.length!==B.length){ crypto.timingSafeEqual(A,A); return false; } return crypto.timingSafeEqual(A,B); }
function publicUser(u) { return { id:u.id, username:u.username, name:u.name, role:u.role, active:u.active, createdAt:u.createdAt }; }
function cookieOptions() { return { httpOnly:true, sameSite:'lax', secure:IS_PRODUCTION, maxAge:7*24*60*60*1000, path:'/' }; }
function issueSession(res,user) { res.cookie('qc_token', jwt.sign({id:user.id,username:user.username,role:user.role}, JWT_SECRET, {expiresIn:'7d',algorithm:'HS256'}), cookieOptions()); }
function requireAuth(req,res,next){ const token=req.cookies.qc_token; if(!token)return res.status(401).json({error:'Not logged in'}); try{const payload=jwt.verify(token,JWT_SECRET,{algorithms:['HS256']}); const user=store.getData().users.find(u=>u.id===payload.id); if(!user||!user.active)return res.status(401).json({error:'Account not found or deactivated'}); req.user=user; next();}catch{res.clearCookie('qc_token',cookieOptions()); return res.status(401).json({error:'Session expired, please log in again'});} }
function requireAdmin(req,res,next){ if(req.user.role!=='admin')return res.status(403).json({error:'Admins only'}); next(); }
function requireIntegrationKey(req,res,next){ const key=req.get('X-QuiverCRM-Key')||(req.get('Authorization')||'').replace(/^Bearer\s+/i,''); if(!key||!safeEqual(key,INTEGRATION_KEY))return res.status(401).json({error:'Invalid or missing integration key'}); next(); }
async function audit(userId, action, entityType, entityId, details={}) { const d=store.getData(); d.activity.unshift({id:newId('ACT'), userId:userId||null, userName:userId?(d.users.find(u=>u.id===userId)?.name||'Unknown'):'System', action, entityType, entityId:entityId||null, details, at:now()}); if(d.activity.length>10000)d.activity.length=10000; await store.save(); }
function ensureOrderMetrics(o){ o.pipelineStage=o.pipelineStage||o.status||'new'; o.status=o.pipelineStage; o.stageHistory=o.stageHistory||[{stage:o.pipelineStage,at:o.receivedAt||o.createdAt||now(),by:null}]; o.assignmentHistory=o.assignmentHistory||[]; o.handlingStartedAt=o.handlingStartedAt||null; o.firstHandledAt=o.firstHandledAt||null; o.completedAt=o.completedAt||null; o.assignedTo=o.assignedTo||null; o.assignedToName=o.assignedToName||null; return o; }
function taskDurationMs(t){ if(!t.startedAt)return 0; return Math.max(0,new Date(t.completedAt||t.updatedAt||now())-new Date(t.startedAt)); }
function minutes(ms){ return Math.round(ms/60000*10)/10; }

app.get('/api/status',(_req,res)=>res.json({hasAdmin:store.getData().users.some(u=>u.role==='admin'), redis:true}));
app.post('/api/setup',setupLimiter,async(req,res)=>{const d=store.getData(); if(d.users.some(u=>u.role==='admin'))return res.status(400).json({error:'An admin account already exists'}); const {username,password,setupKey,name}=req.body||{}; if(!setupKey||!safeEqual(setupKey,SETUP_KEY))return res.status(403).json({error:'Invalid setup key'}); if(!/^[a-zA-Z0-9_.-]{3,40}$/.test(String(username||'')))return res.status(400).json({error:'Invalid username'}); if(!password||String(password).length<10)return res.status(400).json({error:'Use a password of at least 10 characters'}); const user={id:newId('U'),username:String(username),passwordHash:await bcrypt.hash(String(password),12),name:cleanText(name,80)||String(username),role:'admin',active:true,createdAt:now()}; d.users.push(user); await store.save(); issueSession(res,user); await audit(user.id,'admin_setup','user',user.id); res.json({ok:true,user:publicUser(user)});});
app.post('/api/login',loginLimiter,async(req,res)=>{const d=store.getData(); const {username,password}=req.body||{}; const user=d.users.find(u=>u.username===username); if(!user||!user.active)return res.status(401).json({error:'Incorrect username or password'}); if(!await bcrypt.compare(String(password||''),user.passwordHash))return res.status(401).json({error:'Incorrect username or password'}); issueSession(res,user); await audit(user.id,'login','session',user.id); res.json({ok:true,user:publicUser(user)});});
app.post('/api/logout',async(req,res)=>{const token=req.cookies.qc_token; let uid=null; try{uid=token?jwt.verify(token,JWT_SECRET,{algorithms:['HS256']}).id:null;}catch{} res.clearCookie('qc_token',cookieOptions()); if(uid)await audit(uid,'logout','session',uid); res.json({ok:true});});
app.get('/api/me',requireAuth,(req,res)=>res.json(publicUser(req.user)));

/* Users */
app.get('/api/admin/users',requireAuth,requireAdmin,(_req,res)=>res.json(store.getData().users.map(publicUser)));
app.post('/api/admin/users',requireAuth,requireAdmin,async(req,res)=>{const d=store.getData(); const {username,password,name,role}=req.body||{}; if(!/^[a-zA-Z0-9_.-]{3,40}$/.test(String(username||'')))return res.status(400).json({error:'Invalid username'}); if(d.users.some(u=>u.username===username))return res.status(400).json({error:'That username is already taken'}); if(!password||String(password).length<8)return res.status(400).json({error:'Use a password of at least 8 characters'}); if(!['admin','agent'].includes(role))return res.status(400).json({error:'Role must be admin or agent'}); const u={id:newId('U'),username:String(username),passwordHash:await bcrypt.hash(String(password),12),name:cleanText(name,80)||String(username),role,active:true,createdAt:now()}; d.users.push(u); await store.save(); await audit(req.user.id,'create_user','user',u.id,{role:u.role}); res.json(publicUser(u));});
app.patch('/api/admin/users/:id',requireAuth,requireAdmin,async(req,res)=>{const d=store.getData(),u=d.users.find(x=>x.id===req.params.id); if(!u)return res.status(404).json({error:'User not found'}); const {name,role,active,password}=req.body||{}; if(name!==undefined)u.name=cleanText(name,80)||u.name; if(role!==undefined){if(!['admin','agent'].includes(role))return res.status(400).json({error:'Invalid role'}); if(u.role==='admin'&&role!=='admin'&&d.users.filter(x=>x.role==='admin'&&x.active).length<=1)return res.status(400).json({error:'At least one active admin must remain'}); u.role=role;} if(active!==undefined){if(u.role==='admin'&&!active&&d.users.filter(x=>x.role==='admin'&&x.active).length<=1)return res.status(400).json({error:'At least one active admin must remain'});u.active=!!active;} if(password){if(String(password).length<8)return res.status(400).json({error:'Use a password of at least 8 characters'});u.passwordHash=await bcrypt.hash(String(password),12);} await store.save(); await audit(req.user.id,'update_user','user',u.id,{active:u.active,role:u.role}); res.json(publicUser(u));});
app.delete('/api/admin/users/:id',requireAuth,requireAdmin,async(req,res)=>{const d=store.getData(),u=d.users.find(x=>x.id===req.params.id); if(!u)return res.status(404).json({error:'User not found'}); if(u.role==='admin'&&d.users.filter(x=>x.role==='admin').length<=1)return res.status(400).json({error:'At least one admin must remain'}); d.users=d.users.filter(x=>x.id!==req.params.id); d.tasks.forEach(t=>{if(t.assignedTo===req.params.id){t.assignedTo=null;t.assignedToName=null;}}); d.orders.forEach(o=>{if(o.assignedTo===req.params.id){o.assignedTo=null;o.assignedToName=null;}}); await store.save(); await audit(req.user.id,'delete_user','user',req.params.id); res.json({ok:true});});

/* Orders + pipeline */
app.get('/api/orders',requireAuth,(_req,res)=>res.json(store.getData().orders.map(ensureOrderMetrics)));
app.patch('/api/orders/:id',requireAuth,async(req,res)=>{const d=store.getData(),o=d.orders.find(x=>x.id===req.params.id); if(!o)return res.status(404).json({error:'Order not found'}); ensureOrderMetrics(o); const {status,pipelineStage,assignedTo}=req.body||{}; const nextStage=pipelineStage||status; if(nextStage!==undefined&&!PIPELINE_STAGES.includes(nextStage))return res.status(400).json({error:'Invalid pipeline stage'}); if(nextStage!==undefined&&nextStage!==o.pipelineStage){o.pipelineStage=nextStage;o.status=nextStage;o.stageHistory.push({stage:nextStage,at:now(),by:req.user.id}); if(nextStage==='processing'&&!o.handlingStartedAt)o.handlingStartedAt=now(); if(!o.firstHandledAt&&nextStage!=='new')o.firstHandledAt=now(); if(['fulfilled','won','lost','cancelled'].includes(nextStage))o.completedAt=now();}
 if(assignedTo!==undefined){if(req.user.role!=='admin')return res.status(403).json({error:'Only admins can assign order handling work'});if(assignedTo===null||assignedTo===''){o.assignedTo=null;o.assignedToName=null;}else{const u=d.users.find(x=>x.id===assignedTo&&x.active);if(!u)return res.status(400).json({error:'Assigned user not found or inactive'});o.assignedTo=u.id;o.assignedToName=u.name;o.assignmentHistory.push({userId:u.id,userName:u.name,at:now(),by:req.user.id});if(!o.handlingStartedAt)o.handlingStartedAt=now();if(!o.firstHandledAt)o.firstHandledAt=now();}}
 await store.save(); await audit(req.user.id,'update_order','order',o.id,{pipelineStage:o.pipelineStage,assignedTo:o.assignedTo}); res.json(o);});

/* Customers */
app.get('/api/customers',requireAuth,(_req,res)=>res.json(store.getData().customers));
app.post('/api/customers/:id/notes',requireAuth,async(req,res)=>{const c=store.getData().customers.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Customer not found'});const text=cleanText(req.body?.text,1000);if(!text)return res.status(400).json({error:'Note text is required'});if(!Array.isArray(c.notes))c.notes=c.notes?[{id:newId('N'),text:String(c.notes),authorId:null,authorName:'Unknown',at:c.lastOrderAt||now()}]:[];const note={id:newId('N'),text,authorId:req.user.id,authorName:req.user.name,at:now()};c.notes.unshift(note);await store.save();await audit(req.user.id,'add_customer_note','customer',c.id);res.json(c);});

/* Tasks / order handling */
app.get('/api/tasks',requireAuth,(req,res)=>{const tasks=store.getData().tasks;if(req.user.role==='admin')return res.json(tasks);res.json(tasks.filter(t=>t.assignedTo===req.user.id));});
app.post('/api/tasks',requireAuth,requireAdmin,async(req,res)=>{const d=store.getData(),{title,description,assignedTo,relatedOrderId,relatedCustomerId,dueDate,priority}=req.body||{};const titleClean=cleanText(title,150);if(!titleClean)return res.status(400).json({error:'Task title is required'});const assignee=assignedTo?d.users.find(u=>u.id===assignedTo&&u.active):null;if(assignedTo&&!assignee)return res.status(400).json({error:'Assigned user not found or inactive'});if(!['low','medium','high'].includes(priority))return res.status(400).json({error:'Invalid priority'});let dueIso=null;if(dueDate){const p=new Date(dueDate);if(isNaN(p.getTime()))return res.status(400).json({error:'Invalid due date'});dueIso=p.toISOString();}const t={id:newId('T'),title:titleClean,description:cleanText(description,1000),assignedTo:assignee?.id||null,assignedToName:assignee?.name||null,createdBy:req.user.id,createdByName:req.user.name,relatedOrderId:cleanText(relatedOrderId,100)||null,relatedCustomerId:cleanText(relatedCustomerId,100)||null,dueDate:dueIso,priority,status:'open',createdAt:now(),updatedAt:now(),startedAt:null,completedAt:null,reassignments:[]};d.tasks.push(t);if(t.relatedOrderId){const o=d.orders.find(x=>x.id===t.relatedOrderId);if(o){ensureOrderMetrics(o);if(t.assignedTo){o.assignedTo=t.assignedTo;o.assignedToName=t.assignedToName;o.assignmentHistory.push({userId:t.assignedTo,userName:t.assignedToName,at:now(),by:req.user.id});}if(o.pipelineStage==='new'){o.pipelineStage='processing';o.status='processing';o.handlingStartedAt=o.handlingStartedAt||now();o.firstHandledAt=o.firstHandledAt||now();o.stageHistory.push({stage:'processing',at:now(),by:req.user.id});}}}await store.save();await audit(req.user.id,'create_task','task',t.id,{assignedTo:t.assignedTo,relatedOrderId:t.relatedOrderId});res.json(t);});
app.patch('/api/tasks/:id',requireAuth,async(req,res)=>{const d=store.getData(),t=d.tasks.find(x=>x.id===req.params.id);if(!t)return res.status(404).json({error:'Task not found'});const admin=req.user.role==='admin',assignee=t.assignedTo===req.user.id;if(!admin&&!assignee)return res.status(403).json({error:'Not your task'});const {title,description,assignedTo,dueDate,priority,status}=req.body||{};const before=t.status;if(admin){if(title!==undefined){const x=cleanText(title,150);if(!x)return res.status(400).json({error:'Task title is required'});t.title=x;}if(description!==undefined)t.description=cleanText(description,1000);if(priority!==undefined){if(!['low','medium','high'].includes(priority))return res.status(400).json({error:'Invalid priority'});t.priority=priority;}if(status!==undefined){if(!TASK_STATUSES.includes(status))return res.status(400).json({error:'Invalid status'});t.status=status;}if(dueDate!==undefined){if(!dueDate)t.dueDate=null;else{const p=new Date(dueDate);if(isNaN(p.getTime()))return res.status(400).json({error:'Invalid due date'});t.dueDate=p.toISOString();}}if(assignedTo!==undefined){const old=t.assignedTo;if(!assignedTo){t.assignedTo=null;t.assignedToName=null;}else{const u=d.users.find(x=>x.id===assignedTo&&x.active);if(!u)return res.status(400).json({error:'Assigned user not found or inactive'});t.assignedTo=u.id;t.assignedToName=u.name;if(old!==u.id)t.reassignments.push({from:old,to:u.id,at:now(),by:req.user.id});}}}else if(status!==undefined){if(!TASK_STATUSES.includes(status))return res.status(400).json({error:'Invalid status'});t.status=status;} if(before!=='in_progress'&&t.status==='in_progress'&&!t.startedAt)t.startedAt=now();if(t.status==='done'&&!t.completedAt)t.completedAt=now();t.updatedAt=now();if(t.relatedOrderId){const o=d.orders.find(x=>x.id===t.relatedOrderId);if(o){ensureOrderMetrics(o);if(t.assignedTo){o.assignedTo=t.assignedTo;o.assignedToName=t.assignedToName;}if(t.status==='in_progress'&&o.pipelineStage==='new'){o.pipelineStage='processing';o.status='processing';o.handlingStartedAt=o.handlingStartedAt||t.startedAt;o.firstHandledAt=o.firstHandledAt||t.startedAt;o.stageHistory.push({stage:'processing',at:t.startedAt,by:t.assignedTo||req.user.id});}if(t.status==='done'&&['new','contacted','processing','awaiting_payment'].includes(o.pipelineStage)){o.pipelineStage='fulfilled';o.status='fulfilled';o.completedAt=o.completedAt||t.completedAt;o.stageHistory.push({stage:'fulfilled',at:t.completedAt,by:req.user.id});}}}await store.save();await audit(req.user.id,'update_task','task',t.id,{status:t.status,assignedTo:t.assignedTo});res.json(t);});
app.delete('/api/tasks/:id',requireAuth,requireAdmin,async(req,res)=>{const d=store.getData();d.tasks=d.tasks.filter(t=>t.id!==req.params.id);await store.save();await audit(req.user.id,'delete_task','task',req.params.id);res.json({ok:true});});

/* One-click reporting */
app.get('/api/admin/reports/overview',requireAuth,requireAdmin,(_req,res)=>{const d=store.getData();d.orders.forEach(ensureOrderMetrics);const orders=d.orders;const tasks=d.tasks;const byStage={};PIPELINE_STAGES.forEach(s=>byStage[s]=0);orders.forEach(o=>byStage[o.pipelineStage]++);const revenue=orders.filter(o=>['won','fulfilled'].includes(o.pipelineStage)).reduce((s,o)=>s+Number(o.total||0),0);const avgHandle=orders.filter(o=>o.handlingStartedAt&&o.completedAt).reduce((s,o)=>s+(new Date(o.completedAt)-new Date(o.handlingStartedAt)),0);const handled=orders.filter(o=>o.handlingStartedAt&&o.completedAt).length;const users=d.users.map(u=>{const ut=tasks.filter(t=>t.assignedTo===u.id);const done=ut.filter(t=>t.status==='done');const dur=ut.reduce((s,t)=>s+taskDurationMs(t),0);const assignedOrders=orders.filter(o=>o.assignedTo===u.id);const ua=d.activity.filter(a=>a.userId===u.id);const hourCounts={};ua.forEach(a=>{const h=new Date(a.at).getHours();hourCounts[h]=(hourCounts[h]||0)+1;});const busiest=Object.entries(hourCounts).sort((a,b)=>b[1]-a[1])[0];return {id:u.id,name:u.name,username:u.username,role:u.role,active:u.active,tasks:ut.length,tasksDone:done.length,totalTaskMinutes:minutes(dur),avgTaskMinutes:done.length?minutes(dur/done.length):0,ordersHandled:assignedOrders.length,openTasks:ut.filter(t=>t.status!=='done').length,activityCount:ua.length,firstActivityAt:ua.length?ua[ua.length-1].at:null,lastActivityAt:ua.length?ua[0].at:null,busiestHour:busiest?String(busiest[0]).padStart(2,'0')+':00–'+String((Number(busiest[0])+1)%24).padStart(2,'0')+':00':'—'};});const activity24=d.activity.filter(a=>Date.now()-new Date(a.at).getTime()<86400000);res.json({generatedAt:now(),totals:{orders:orders.length,newOrders:orders.filter(o=>o.pipelineStage==='new').length,openTasks:tasks.filter(t=>t.status!=='done').length,customers:d.customers.length,revenue,avgHandlingMinutes:handled?minutes(avgHandle/handled):0,completedOrders:handled},pipeline:byStage,users,activity24h:activity24.length,activityCount:d.activity.length});});
app.get('/api/admin/reports/activity',requireAuth,requireAdmin,(req,res)=>{const d=store.getData();const limit=Math.min(Math.max(Number(req.query.limit)||200,1),1000);res.json(d.activity.slice(0,limit));});
app.get('/api/admin/reports/order/:id',requireAuth,requireAdmin,(req,res)=>{const d=store.getData(),o=d.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Order not found'});ensureOrderMetrics(o);const tasks=d.tasks.filter(t=>t.relatedOrderId===o.id).map(t=>({...t,durationMinutes:minutes(taskDurationMs(t))}));const activity=d.activity.filter(a=>a.entityType==='order'&&a.entityId===o.id);res.json({order:o,tasks,activity});});

/* Integration: inbound orders */
app.post('/api/integrations/orders',integrationLimiter,requireIntegrationKey,async(req,res)=>{const d=store.getData(),b=req.body||{};const externalId=cleanText(b.externalId,100),source=cleanText(b.source,60)||'External store',customerName=cleanText(b.customerName,150),phone=normalizePhone(b.phone);if(!customerName||!phone)return res.status(400).json({error:'customerName and phone are required'});if(externalId&&d.orders.some(o=>o.externalId===externalId&&o.source===source))return res.json({ok:true,duplicate:true});const items=Array.isArray(b.items)?b.items.slice(0,50).map(i=>({id:cleanText(i?.id,100),name:cleanText(i?.name,150),price:Number.isFinite(Number(i?.price))?Number(i.price):0,qty:Number.isInteger(Number(i?.qty))?Number(i.qty):0})):[];const total=Number.isFinite(Number(b.total))?Number(b.total):items.reduce((s,i)=>s+i.price*i.qty,0);const createdAt=b.createdAt&&!isNaN(Date.parse(b.createdAt))?new Date(b.createdAt).toISOString():now();const receivedAt=now();const order={id:newId('QORD'),externalId:externalId||null,source,items,total,currency:cleanText(b.currency,10)||'USD',customerName,phone,address:cleanText(b.address,500),notes:cleanText(b.notes,500),status:'new',pipelineStage:'new',createdAt,receivedAt,stageHistory:[{stage:'new',at:receivedAt,by:null}],assignmentHistory:[],assignedTo:null,assignedToName:null,handlingStartedAt:null,firstHandledAt:null,completedAt:null};d.orders.unshift(order);let customer=d.customers.find(c=>c.phone===phone);if(customer){customer.name=customerName;if(order.address)customer.address=order.address;customer.orderCount=(customer.orderCount||0)+1;customer.totalSpent=(customer.totalSpent||0)+total;customer.lastOrderAt=createdAt;}else d.customers.push({id:newId('C'),name:customerName,phone,address:order.address,source,orderCount:1,totalSpent:total,lastOrderAt:createdAt,notes:[]});await store.save();res.json({ok:true,orderId:order.id});});

app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Server error'});});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));

(async()=>{try{await store.init(); app.listen(PORT,()=>console.log(`QuiverCRM running on http://localhost:${PORT} with Upstash Redis`));}catch(e){console.error('Failed to initialize Upstash Redis:',e);process.exit(1);}})();
